steps:
  # Step 1: Build the Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/backend-app:latest', '.']

  # Step 2: Build the Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/frontend-app:latest', './frontend']  # Assuming frontend code is in ./frontend

  # Step 3: Deploy the Backend image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/myapp-deployment', 'myapp=gcr.io/${_PROJECT_ID}/backend-app:latest', '--namespace=default']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

  # Step 4: Deploy the Frontend image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/myapp-deployment', 'frontend=gcr.io/${_PROJECT_ID}/frontend-app:latest', '--namespace=default']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/${_PROJECT_ID}/backend-app:latest'
  - 'gcr.io/${_PROJECT_ID}/frontend-app:latest'

substitutions:
  _PROJECT_ID: 'iron-wave-434723-e4'  # Your GCP Project ID
  _ZONE: 'northamerica-northeast1'
  _CLUSTER_NAME: 'my-flask-cluster'
